# Generated by Django 2.2.13 on 2020-06-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
